version: "3.4"

services:
  my-app:
    container_name: my-next-app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-next-app-image
    ports:
      - "3010:3000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "20"
